vim.cmd 'hi clear'
vim.g.colors_name = 'jetdark'
vim.o.termguicolors = true

local hi = vim.api.nvim_set_hl

-- UI
hi(0, 'Normal',         { fg = '#bcbec4', bg = '#1e1f22' })
hi(0, 'NormalNC',       { fg = '#bcbec4', bg = '#1e1f22' })
hi(0, 'NormalFloat',    { fg = '#bcbec4', bg = '#2b2d30' })
hi(0, 'FloatBorder',    { fg = '#647378', bg = '#2b2d30' })
hi(0, 'CursorLine',     { bg = '#273235' })
hi(0, 'CursorLineNr',   { fg = '#c6c6c6', bold = true })
hi(0, 'LineNr',         { fg = '#4b5059' })
hi(0, 'Visual',         { bg = '#264f78' })
hi(0, 'VisualNOS',      { bg = '#264f78' })
hi(0, 'Pmenu',          { fg = '#bcbec4', bg = '#2b2d30' })
hi(0, 'PmenuSel',       { bg = '#43454a' })
hi(0, 'PmenuSbar',      { bg = '#2b2d30' })
hi(0, 'PmenuThumb',     { bg = '#084458' })
hi(0, 'StatusLine',     { fg = '#a8abb0', bg = '#191a1c' })
hi(0, 'StatusLineNC',   { fg = '#4b5059', bg = '#191a1c' })
hi(0, 'TabLine',        { fg = '#808080', bg = '#252a2f' })
hi(0, 'TabLineFill',    { bg = '#191a1c' })
hi(0, 'TabLineSel',     { fg = '#ffffff', bg = '#084458' })
hi(0, 'WinSeparator',   { fg = '#647378' })
hi(0, 'VertSplit',      { fg = '#647378' })
hi(0, 'SignColumn',     { bg = '#1e1f22' })
hi(0, 'FoldColumn',     { fg = '#4b5059', bg = '#1e1f22' })
hi(0, 'Folded',         { fg = '#7a7e85', bg = '#252a2f' })
hi(0, 'ColorColumn',    { bg = '#252a2f' })
hi(0, 'Cursor',         { fg = '#1e1f22', bg = '#aeafad' })
hi(0, 'TermCursor',     { fg = '#1e1f22', bg = '#aeafad' })
hi(0, 'MatchParen',     { bg = '#3a3d41', bold = true })
hi(0, 'Search',         { fg = '#ffffff', bg = '#02917c' })
hi(0, 'IncSearch',      { fg = '#ffffff', bg = '#02917c' })
hi(0, 'CurSearch',      { fg = '#ffffff', bg = '#02917c' })
hi(0, 'NonText',        { fg = '#4b5059' })
hi(0, 'SpecialKey',     { fg = '#4b5059' })
hi(0, 'Whitespace',     { fg = '#3a3d41' })
hi(0, 'EndOfBuffer',    { fg = '#1e1f22' })
hi(0, 'Directory',      { fg = '#56a8f5' })
hi(0, 'Title',          { fg = '#cf8e6d', bold = true })
hi(0, 'Question',       { fg = '#56a8f5' })
hi(0, 'MoreMsg',        { fg = '#6aab73' })
hi(0, 'WarningMsg',     { fg = '#cca700' })
hi(0, 'ErrorMsg',       { fg = '#f14c4c', bold = true })
hi(0, 'WinBar',         { fg = '#bcbec4', bg = '#1e1f22' })
hi(0, 'WinBarNC',       { fg = '#4b5059', bg = '#1e1f22' })
hi(0, 'WildMenu',       { fg = '#ffffff', bg = '#02917c' })

-- Syntax
hi(0, 'Comment',        { fg = '#7a7e85', italic = true })
hi(0, 'String',         { fg = '#6aab73' })
hi(0, 'Character',      { fg = '#6aab73' })
hi(0, 'Number',         { fg = '#2aacb8' })
hi(0, 'Float',          { fg = '#2aacb8' })
hi(0, 'Boolean',        { fg = '#cf8e6d' })
hi(0, 'Constant',       { fg = '#c77dbb' })
hi(0, 'Identifier',     { fg = '#bcbec4' })
hi(0, 'Function',       { fg = '#56a8f5' })
hi(0, 'Statement',      { fg = '#cf8e6d' })
hi(0, 'Keyword',        { fg = '#cf8e6d' })
hi(0, 'Conditional',    { fg = '#cf8e6d' })
hi(0, 'Repeat',         { fg = '#cf8e6d' })
hi(0, 'Operator',       { fg = '#bcbec4' })
hi(0, 'Exception',      { fg = '#cf8e6d' })
hi(0, 'Label',          { fg = '#cf8e6d' })
hi(0, 'PreProc',        { fg = '#cf8e6d' })
hi(0, 'Include',        { fg = '#cf8e6d' })
hi(0, 'Define',         { fg = '#cf8e6d' })
hi(0, 'Macro',          { fg = '#cf8e6d' })
hi(0, 'Type',           { fg = '#8888c6' })
hi(0, 'StorageClass',   { fg = '#cf8e6d' })
hi(0, 'Structure',      { fg = '#8888c6' })
hi(0, 'Typedef',        { fg = '#8888c6' })
hi(0, 'Special',        { fg = '#cf8e6d' })
hi(0, 'SpecialChar',    { fg = '#cf8e6d' })
hi(0, 'Tag',            { fg = '#d5b778' })
hi(0, 'Delimiter',      { fg = '#bcbec4' })
hi(0, 'SpecialComment', { fg = '#7a7e85', bold = true })
hi(0, 'Underlined',     { fg = '#56a8f5', underline = true })
hi(0, 'Error',          { fg = '#f14c4c' })
hi(0, 'Todo',           { fg = '#b3ae60', bold = true })

-- Treesitter
hi(0, '@variable',                { fg = '#bcbec4' })
hi(0, '@variable.builtin',       { fg = '#94558d' })
hi(0, '@variable.parameter',     { fg = '#aa4926' })
hi(0, '@variable.member',        { fg = '#c77dbb' })
hi(0, '@constant',               { fg = '#c77dbb' })
hi(0, '@constant.builtin',       { fg = '#cf8e6d' })
hi(0, '@module',                  { fg = '#bcbec4' })
hi(0, '@string',                  { fg = '#6aab73' })
hi(0, '@string.escape',          { fg = '#cf8e6d' })
hi(0, '@string.special',         { fg = '#cf8e6d' })
hi(0, '@character',              { fg = '#6aab73' })
hi(0, '@number',                  { fg = '#2aacb8' })
hi(0, '@boolean',                 { fg = '#cf8e6d' })
hi(0, '@float',                   { fg = '#2aacb8' })
hi(0, '@function',                { fg = '#56a8f5' })
hi(0, '@function.builtin',       { fg = '#8888c6' })
hi(0, '@function.call',          { fg = '#56a8f5' })
hi(0, '@function.method',        { fg = '#56a8f5' })
hi(0, '@function.method.call',   { fg = '#56a8f5' })
hi(0, '@constructor',            { fg = '#d5b778' })
hi(0, '@keyword',                 { fg = '#cf8e6d' })
hi(0, '@keyword.function',       { fg = '#cf8e6d' })
hi(0, '@keyword.return',         { fg = '#cf8e6d' })
hi(0, '@keyword.operator',       { fg = '#cf8e6d' })
hi(0, '@keyword.import',         { fg = '#cf8e6d' })
hi(0, '@keyword.conditional',    { fg = '#cf8e6d' })
hi(0, '@keyword.repeat',         { fg = '#cf8e6d' })
hi(0, '@keyword.exception',      { fg = '#cf8e6d' })
hi(0, '@operator',                { fg = '#bcbec4' })
hi(0, '@punctuation',             { fg = '#bcbec4' })
hi(0, '@punctuation.bracket',    { fg = '#bcbec4' })
hi(0, '@punctuation.delimiter',  { fg = '#bcbec4' })
hi(0, '@punctuation.special',    { fg = '#cf8e6d' })
hi(0, '@comment',                 { fg = '#7a7e85', italic = true })
hi(0, '@type',                    { fg = '#8888c6' })
hi(0, '@type.builtin',           { fg = '#8888c6' })
hi(0, '@type.qualifier',         { fg = '#cf8e6d' })
hi(0, '@type.python',            { fg = '#bcbec4' })
hi(0, '@variable.member.python', { fg = '#bcbec4' })
hi(0, '@property.python',        { fg = '#bcbec4' })
hi(0, '@attribute',               { fg = '#b3ae60' })
hi(0, '@property',                { fg = '#c77dbb' })
hi(0, '@tag',                     { fg = '#d5b778' })
hi(0, '@tag.attribute',          { fg = '#c77dbb' })
hi(0, '@tag.delimiter',          { fg = '#d5b778' })
hi(0, '@markup.heading',         { fg = '#cf8e6d', bold = true })
hi(0, '@markup.link',            { fg = '#56a8f5' })
hi(0, '@markup.link.url',        { fg = '#56a8f5', underline = true })
hi(0, '@markup.raw',             { fg = '#6aab73' })
hi(0, '@markup.list',            { fg = '#cf8e6d' })

-- Diagnostics
hi(0, 'DiagnosticError',         { fg = '#f14c4c' })
hi(0, 'DiagnosticWarn',          { fg = '#cca700' })
hi(0, 'DiagnosticInfo',          { fg = '#59a4f9' })
hi(0, 'DiagnosticHint',          { fg = '#eeeeee' })
hi(0, 'DiagnosticUnderlineError', { undercurl = true, sp = '#f14c4c' })
hi(0, 'DiagnosticUnderlineWarn',  { undercurl = true, sp = '#cca700' })
hi(0, 'DiagnosticUnderlineInfo',  { undercurl = true, sp = '#59a4f9' })
hi(0, 'DiagnosticUnderlineHint',  { undercurl = true, sp = '#eeeeee' })

-- Git signs
hi(0, 'GitSignsAdd',    { fg = '#487e02' })
hi(0, 'GitSignsChange', { fg = '#1b81a8' })
hi(0, 'GitSignsDelete', { fg = '#f14c4c' })
hi(0, 'DiffAdd',        { bg = '#2a3b2a' })
hi(0, 'DiffChange',     { bg = '#1a2a3a' })
hi(0, 'DiffDelete',     { bg = '#3b2a2a' })
hi(0, 'DiffText',       { bg = '#264f78' })

-- NvimTree
hi(0, 'NvimTreeNormal',       { fg = '#bcbec4', bg = '#191a1c' })
hi(0, 'NvimTreeNormalNC',     { fg = '#bcbec4', bg = '#191a1c' })
hi(0, 'NvimTreeEndOfBuffer',  { fg = '#191a1c' })
hi(0, 'NvimTreeFolderIcon',   { fg = '#56a8f5' })
hi(0, 'NvimTreeFolderName',   { fg = '#bcbec4' })
hi(0, 'NvimTreeOpenedFolderName', { fg = '#bcbec4', bold = true })
hi(0, 'NvimTreeRootFolder',   { fg = '#bbbbbb', bold = true })
hi(0, 'NvimTreeGitDirty',     { fg = '#1b81a8' })
hi(0, 'NvimTreeGitNew',       { fg = '#487e02' })
hi(0, 'NvimTreeGitIgnored',   { fg = '#c69568' })
hi(0, 'NvimTreeWinSeparator', { fg = '#647378' })
hi(0, 'NvimTreeCursorLine',   { bg = '#273235' })

-- Telescope
hi(0, 'TelescopeBorder',        { fg = '#647378' })
hi(0, 'TelescopePromptBorder',  { fg = '#647378' })
hi(0, 'TelescopeResultsBorder', { fg = '#647378' })
hi(0, 'TelescopePreviewBorder', { fg = '#647378' })
hi(0, 'TelescopeMatching',      { fg = '#548af7' })
hi(0, 'TelescopeSelection',     { bg = '#43454a' })

-- Indent blankline
hi(0, 'IblIndent', { fg = '#282a2e' })
hi(0, 'IblScope',  { fg = '#353840' })

-- Lualine (uses theme auto-detection, but set bg for consistency)
hi(0, 'lualine_c_normal', { fg = '#bcbec4', bg = '#191a1c' })
